### PR TITLE
Bump version 5.2.6

### PR DESCRIPTION
**Pull request by jburel**
also bump BF version to 5.1.10

### CODE REVIEW

**Comment by mtbc** [comment]
Have we CI for this or should it be run locally? (I don't know what [OMERO-DEV-merge-maven-client](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-maven-client/) is but it doesn't look happy.)

**Comment by jburel** [comment]
we use to check with the CI job, but has not been happy for a bit
This will require some investigation.
You can run it locally 
cc @dominikl

**Comment by dominikl** [comment]
Ran it locally, works fine, bioformats 5.1.10 and blitz 5.2.6 is downloaded and used, like expected 👍

**Comment by jburel** [comment]
Merging

**Pull request merged**
