### PR TITLE
Gateway 5.10.0

### PR DESCRIPTION
**Pull request by jburel**
Bump gateway version

### CODE REVIEW

**Comment by jburel** [comment]
This PR needs https://github.com/ome/minimal-omero-client/pull/68 to become green

**Review by dominikl — APPROVED** [review]
Thanks JM, looks good 👍 Not updated the version in a while.

**Comment by jburel** [comment]
I had a PR opened but it did not get merged :-)

**Comment by dominikl** [comment]
Hm, looks like gradle can't find the gateway.jar...
`Could not resolve org.openmicroscopy:omero-gateway:5.10.0.`

**Comment by jburel** [comment]
@dominikl The problem was due to the Dockerfile still using Java 1.8
I have updated the Docker image since "openjdk" image is deprecated
The build is now green

**Comment by dominikl** [comment]
👍  Ah yes, looks good now.

**Pull request merged**
