### PR TITLE
Gateway

### PR DESCRIPTION
**Pull request by jburel**
Testing the changes.
Travis builds are green.

To test:
 * checkout code
 * import maven project
 * set the credentials in the main method.
 * Run the example

possible action:
 * parse args to set credentials

### CODE REVIEW

**Comment by joshmoore** [comment]
Two quick thoughts:

 * changes to the version should happen in https://github.com/ome/pom-omero-client (we don't currently have a merge workflow for updating both at the same time)
 * use of `ome.staging` should be avoided except for during testing.

**Comment by jburel** [comment]
@joshmoore: Yes. I forgot to mention it in the description. The use of staging is only for testing
 and will be remove post release.
No plan to merge before release.

**Comment by mtbc** [comment]
Took me a minute to figure out how to get the right JARs into my classpath, but:
```
[omero.gateway.model.ProjectData (id=1202), omero.gateway.model.ProjectData (id=1), omero.gateway.model.ProjectData (id=1021), omero.gateway.model.ProjectData (id=1053), omero.gateway.model.ProjectData (id=1054)]
```
Seems fine functionally. :+1:

Bit strange that this PR is against `dev_5_1` but uses Blitz 5.2.0? (Maybe that name relates to BF 5.1?)

**Comment by jburel** [comment]
@mtbc: mainly prep work.

**Comment by jburel** [comment]
replaced by https://github.com/ome/minimal-omero-client/pull/8

**Pull request closed without merging**
